/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as ArtIndexRouteImport } from './routes/art/index'
import { Route as ApiSpotifyAuthRouteImport } from './routes/api/spotify-auth'
import { Route as ApiRecentlyPlayedRouteImport } from './routes/api/recently-played'
import { Route as ApiMediaRouteImport } from './routes/api/media'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtIndexRoute = ArtIndexRouteImport.update({
  id: '/art/',
  path: '/art/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyAuthRoute = ApiSpotifyAuthRouteImport.update({
  id: '/api/spotify-auth',
  path: '/api/spotify-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecentlyPlayedRoute = ApiRecentlyPlayedRouteImport.update({
  id: '/api/recently-played',
  path: '/api/recently-played',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRoute
  '/api/recently-played': typeof ApiRecentlyPlayedRoute
  '/api/spotify-auth': typeof ApiSpotifyAuthRoute
  '/art/': typeof ArtIndexRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRoute
  '/api/recently-played': typeof ApiRecentlyPlayedRoute
  '/api/spotify-auth': typeof ApiSpotifyAuthRoute
  '/art': typeof ArtIndexRoute
  '/dev': typeof DevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRoute
  '/api/recently-played': typeof ApiRecentlyPlayedRoute
  '/api/spotify-auth': typeof ApiSpotifyAuthRoute
  '/art/': typeof ArtIndexRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/media'
    | '/api/recently-played'
    | '/api/spotify-auth'
    | '/art/'
    | '/dev/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/media'
    | '/api/recently-played'
    | '/api/spotify-auth'
    | '/art'
    | '/dev'
  id:
    | '__root__'
    | '/'
    | '/api/media'
    | '/api/recently-played'
    | '/api/spotify-auth'
    | '/art/'
    | '/dev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiRecentlyPlayedRoute: typeof ApiRecentlyPlayedRoute
  ApiSpotifyAuthRoute: typeof ApiSpotifyAuthRoute
  ArtIndexRoute: typeof ArtIndexRoute
  DevIndexRoute: typeof DevIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/': {
      id: '/art/'
      path: '/art'
      fullPath: '/art/'
      preLoaderRoute: typeof ArtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify-auth': {
      id: '/api/spotify-auth'
      path: '/api/spotify-auth'
      fullPath: '/api/spotify-auth'
      preLoaderRoute: typeof ApiSpotifyAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recently-played': {
      id: '/api/recently-played'
      path: '/api/recently-played'
      fullPath: '/api/recently-played'
      preLoaderRoute: typeof ApiRecentlyPlayedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiRecentlyPlayedRoute: ApiRecentlyPlayedRoute,
  ApiSpotifyAuthRoute: ApiSpotifyAuthRoute,
  ArtIndexRoute: ArtIndexRoute,
  DevIndexRoute: DevIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
